services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true

  auth.jwt_manager:
    class: FreedomSex\Services\JWTManager
    public: true
    arguments:
      $secret_key: '%kernel.project_dir%/config/keys/private.key'
      $public_key: '%kernel.project_dir%/config/keys/public.key'
      $pass_phrase: null
      $token_ttl: 300

  FreedomSex\Services\JWTManager: '@auth.jwt_manager'


  FreedomSex\Services\ClientIdentifier: ~

  FreedomSex\AuthBundle\Security\JWTExtractor: ~

  FreedomSex\AuthBundle\Security\JWTAuthenticator: ~

  FreedomSex\AuthBundle\Security\Voters\RequestUidVoter: ~

  FreedomSex\AuthBundle\Security\Voters\UserUidVoter: ~
