services:

  FreedomSex\Services\JWTManager:
    public: true
    arguments:
      - $secret_key: '%kernel.project_dir%/config/keys/private.key'
      - $public_key: '%kernel.project_dir%/config/keys/public.key'
      - $token_ttl: 3600
