services:

  FreedomSex\Services\JWTManager:
    public: true
    arguments:
      $secret_key: '%kernel.project_dir%/config/keys/private.key'
      $public_key: '%kernel.project_dir%/config/keys/public.key'
      $pass_phrase: null
      $token_ttl: 3600


  FreedomSex\AuthBundle\Security\JWTExtractor:
    public: true

  FreedomSex\AuthBundle\Security\JWTAuthenticator:
    public: true
    arguments:
      - '@FreedomSex\Services\JWTManager'
      - '@FreedomSex\AuthBundle\Security\JWTExtractor'
